<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "album".
 *
 * @property int $id
 * @property string $name_vi
 * @property string $image
 * @property int $ord
 * @property int $active
 * @property string $name_en
 * @property string $decription
 *
 * @property Picture[] $pictures
 */
class Album extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'album';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name_vi'], 'required'],
            [['image', 'decription'], 'string'],
            [['ord', 'active'], 'integer'],
            [['name_vi', 'name_en'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name_vi' => 'Tên album',
            'image' => 'Ảnh',
            'ord' => 'Thứ tự',
            'active' => 'Hoạt động',
            'name_en' => 'Name En',
            'decription' => 'Decription',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPictures()
    {
        return $this->hasMany(Picture::className(), ['album_id' => 'id']);
    }
    public function afterDelete()
    {
        $path = dirname(dirname(__DIR__)) . '/images/album/' . $this->image;
        if (is_file($path))
            unlink($path);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
    public function beforeDelete()
    {
        foreach ($this->pictures as $picture){
            $picture->delete();
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
    public function beforeSave($insert)
    {
        $file = UploadedFile::getInstanceByName('imagealbum');
        if (!is_null($file)) {
            $this->image = '/images/album/' . \func::taoduongdan(time() . "-" . $file->name);
            $path = dirname(dirname(__DIR__)) . $this->image;
            $file->saveAs($path);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
