<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "catnew".
 *
 * @property int $id
 * @property string $url
 * @property string $name
 * @property int $position
 * @property int $active
 * @property int $home
 * @property int $ord
 * @property string $seo_title
 * @property string $seo_desc
 * @property string $seo_keyword
 * @property int $lang_id
 * @property int $parent
 *
 * @property News[] $news
 */
class Catnew extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    CONST AdsCatNew=1;
    CONST CatNew=2;

    public static function tableName()
    {
        return 'catnew';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['url', 'seo_desc'], 'string'],
            [['name'], 'required'],
            [['position', 'active', 'home', 'ord', 'lang_id', 'parent'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['seo_title', 'seo_keyword'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'url' => 'Url',
            'name' => 'Name',
            'position' => 'Position',
            'active' => 'Kích hoạt',
            'home' => 'Hiển thị trang chủ',
            'ord' => 'Ord',
            'seo_title' => 'Seo Title',
            'seo_desc' => 'Seo Desc',
            'seo_keyword' => 'Seo Keyword',
            'lang_id' => 'Lang ID',
            'parent' => 'Parent',
        ];
    }
    public static function getExportColumn(){
        return [
            'id' ,
            'url' ,
            'name' ,
            'position' ,
            'active' ,
            'home' ,
            'ord' ,
            'seo_title' ,
            'seo_desc' ,
            'seo_keyword' ,
            'parent' ,
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNews()
    {
        return $this->hasMany(News::className(), ['cat_new_id' => 'id']);
    }
    public static function getAllCat($id){
        if($id=='' || is_null($id))
            return Catnew::find()->all();
        return Catnew::find()->where('id <> :id and parent <> :id',[':id'=>$id])->all();
    }
    public function afterDelete()
    {
        Catnew::updateAll(['parent'=>'-1'],['parent'=>$this->id]);
    }
   public function beforeDelete()
   {
       foreach ($this->news as $new){
           $new->delete();
       }
       return parent::beforeDelete(); // TODO: Change the autogenerated stub
   }
   public static function getPosition(){
        return
        [
            self::CatNew =>'Chuyên mục tin tức bình thường',
            self::AdsCatNew=>'Chuyên mục tin trên header quảng cáo',

        ];
   }
}
