<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "grproduct".
 *
 * @property int $id
 * @property string $name
 * @property int $active
 *
 * @property Grproctag[] $grproctags
 */
class Grproduct extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'grproduct';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'active'], 'required'],
            [['name'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'active' => 'Hiển thị trang chủ',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrproctags()
    {
        return $this->hasMany(Grproctag::className(), ['grproduct_id' => 'id']);
    }
    public function afterSave($insert, $changedAttributes)
    {
        Grproctag::deleteAll(['grproduct_id'=>$this->id]);
        foreach ($_POST['tag'] as $value){
            $newtag = new Grproctag();
            $newtag->tag=$value;
            $newtag->grproduct_id=$this->id;
            $newtag->save();
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
