<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "slides".
 *
 * @property int $id
 * @property string $name
 * @property string $brief
 * @property string $thumb
 * @property string $image
 * @property string $url
 * @property int $ord
 * @property int $active
 * @property string $position
 */
class Slides extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    const MAIN="main";
    const  SUB="proc";
    public static function tableName()
    {
        return 'slides';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['ord', 'active'], 'integer'],
            [['position'], 'string'],
            [['name', 'thumb', 'image', 'url'], 'string', 'max' => 200],
            [['brief'], 'string', 'max' => 500],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên',
            'brief' => 'Mô tả',
            'thumb' => 'Thumb',
            'image' => 'Ảnh',
            'url' => 'Đường dẫn',
            'ord' => 'Thứ tự',
            'active' => 'Hoạt động',
            'position' => 'Vị trí',
        ];
    }

    public function afterDelete()
    {
        $path = dirname(dirname(__DIR__)) . '/images/slides/' . $this->image;
        if (is_file($path))
            unlink($path);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public static function getSlide()
    {
        return self::find()->where(['active' => 1])->orderBy(['ord' => SORT_ASC])->all();
    }

    public static function getSlideByPos($pos)
    {
        return self::find()->where(['position' => $pos, 'active' => 1])->orderBy(['ord' => SORT_ASC])->all();
    }
    public static function getPosition()
    {
        return [
            self::MAIN => 'Slide chính (tỷ lệ 800x300)',
            self::SUB => 'Slide phụ',
        ];
    }
}
